disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - implicit_return
  - closure_end_indentation
  - explicit_init

line_length: 100
indentation:
  width: 4

excluded:
  - Pods
  - fastlane

file_length:
  warning: 300
  error: 500

type_body_length:
  warning: 200
  error: 400

function_body_length:
  warning: 20
  error: 50

type_name:
  min_length: 3
  max_length: 40
  excluded: 
    - iPhone

identifier_name:
  min_length: 3
  max_length: 40
  allowed_symbols: ["_"]

force_try:
  severity: error

explicit_enum_raw_value:
  severity: warning

private_outlet:
  severity: warning

redundant_nil_coalescing:
  severity: warning

unowned_variable_capture:
  severity: warning